stages:
  - linting

php-lint:
  stage: linting
  image: registry.gitlab.com/pipeline-components/php-linter:latest
  script:
    - parallel-lint --colors .

ansible-lint:
  stage: linting
  image: registry.gitlab.com/pipeline-components/ansible-lint:latest
  script:
    - ansible-lint -f codeclimate | python -m json.tool | tee "${CI_PROJECT_DIR}/codeclimate-results.json"
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    reports:
      codequality:
        - "${CI_PROJECT_DIR}/codeclimate-results.json"
    paths:
      - "${CI_PROJECT_DIR}/codeclimate-results.json"