---
- name: Restart apache2 service
  ansible.builtin.service:
    name: apache2
    enabled: true
    state: restarted

- name: Restart rrdcached service
  ansible.builtin.service:
    name: rrdcached
    enabled: true
    state: restarted

- name: Restart rsyslog service
  ansible.builtin.service:
    name: rsyslog
    enabled: true
    state: restarted
