name: Lint and test PHP and Ansible
on: 
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: debian-latest
    steps:
        - uses: actions/checkout@v1

        - name: Run PHP Linter
          uses: michaelw90/PHP-Lint@master
