name: Lint and test PHP and Ansible
on: 
  push:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1

        - name: PHP Linter
          uses: michaelw90/PHP-Lint@master

        - name: Ansible Lint
          uses: ansible/ansible-lint@main
          with:
            args: "-c .config/ansible-lint.yml"
